name: Run Python Script on Schedule

on:
  schedule:
    - cron: "0/30 * * * *"   # every day at 12:00 UTC
  workflow_dispatch:        # optional: allow manual runs

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python run_all_tests_scheduled.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sample_crm.db
          git commit -m "Update database from scheduled run" || echo "No changes to commit"
          git push
